NICTERP/Controllers/AdmissionFormsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NICTERP.Models;
using NICTERP.Models.View_Models;
using NICTERP.Models.NICT;
using System.IO;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
namespace NICTERP.Controllers
{
    [Authorize]
    public class AdmissionFormsController : Controller
    {
        private NICTDbContext db = new NICTDbContext();
        protected int CenterID()
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            return currentUser.CenterID;
        }
        // GET: AdmissionForms
        public ActionResult Index()
        {
            List<AdmissionForm> admissionForms = db.AdmisionForms.ToList();
            return View(admissionForms);
        }

        // GET: AdmissionForms/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
                AdmissionFormViewModel myModel = db.GetViewModel((long)id);
            if (myModel == null)
            {
                return HttpNotFound();
            }
            
            return View(myModel);
        }

        // GET: AdmissionForms/Create
        public ActionResult Create()
        {
            List<SelectListItem> courses = new List<SelectListItem>();
            foreach (var course in db.Courses.ToList())
            {
                courses.Add(new SelectListItem { Value = course.Id.ToString(), Text = course.CourseName });
            }
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var center in db.Centers.ToList())
            {
                items.Add(new SelectListItem { Value = center.CenterId.ToString(), Text = center.CenterName });
            }
            ViewBag.Centers = items;
            ViewBag.Course_Applied = courses;
            AdmissionFormViewModel model = new AdmissionFormViewModel();
            return View(model);
        }

        // POST: AdmissionForms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AdmissionFormViewModel admissionFormViewModel)
        {

            if (ModelState.IsValid)
            {
                AdmissionForm AdmissionForm = new AdmissionForm();
                AdmissionForm.Dated = DateTime.UtcNow;
                AdmissionForm.centerId = admissionFormViewModel.StudentDetail.Center;
                db.AdmisionForms.Add(AdmissionForm);
                db.SaveChanges();
                long form_no = AdmissionForm.Form_No;

                //update formno for all tables
                admissionFormViewModel.Installment.Form_No = form_no;
                admissionFormViewModel.AboutNICT.Form_No = form_no;
                admissionFormViewModel.EduQualification.Form_No = form_no;
                admissionFormViewModel.StudentDetail.Form_No = form_no;
                //check for empty model properties
                if (!admissionFormViewModel.JobExperience.HasAllEmptyProperties())
                {
                    admissionFormViewModel.JobExperience.Form_No = form_no;
                    db.JobExperiences.Add(admissionFormViewModel.JobExperience);
                }
                if (!admissionFormViewModel.KnowledgeOfComp.HasAllEmptyProperties())
                {
                    admissionFormViewModel.KnowledgeOfComp.Form_No = form_no;
                    db.KnowledgeOfComps.Add(admissionFormViewModel.KnowledgeOfComp);
                }


                //check for uploaded files
                if (admissionFormViewModel.Files != null)
                {
                    foreach (var File in admissionFormViewModel.Files)
                    {
                        File.Form_No = form_no;
                        File.Datetime = AdmissionForm.Dated;
                        db.Files.Add(File);
                    }
                }

                admissionFormViewModel.Installment.Duedate = DateTime.UtcNow.AddDays(10);
                admissionFormViewModel.Installment.Datetime = AdmissionForm.Dated;
                admissionFormViewModel.Installment.Balance_Due = 3000 - admissionFormViewModel.Installment.Amount_Paid;

                //update student reg no
                int regNo = db.StudentDetails.Where(y => y.Center.Equals(admissionFormViewModel.StudentDetail.Center)).OrderByDescending(x => x.Reg_No).Select(s => s.Reg_No).FirstOrDefault();
                if (regNo == 0 || regNo == null)
                    regNo++;
                //set the reg number
                admissionFormViewModel.StudentDetail.Reg_No = regNo;


                //add all the models to db
                db.AboutNICTs.Add(admissionFormViewModel.AboutNICT);
                db.EduQualifications.Add(admissionFormViewModel.EduQualification);
                db.StudentDetails.Add(admissionFormViewModel.StudentDetail);
                db.Installments.Add(admissionFormViewModel.Installment);
                db.SaveChanges();

                return RedirectToAction("Details",form_no);
            }
            
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var center in db.Centers.ToList())
            {
                items.Add(new SelectListItem { Value = center.CenterId.ToString(), Text = center.CenterName });
            }
            ViewBag.Centers = items;
            return View(admissionFormViewModel);
        }

        // GET: AdmissionForms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //AdmissionFormViewModel admissionFormViewModel = db.AdmissionFormViewModels.Find(id);
            //if (admissionFormViewModel == null)
            //{
            //    return HttpNotFound();
            //}
            return View();
        }

        // POST: AdmissionForms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id")] AdmissionFormViewModel admissionFormViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admissionFormViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admissionFormViewModel);
        }

        // GET: AdmissionForms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // AdmissionFormViewModel admissionFormViewModel = db.AdmissionFormViewModels.Find(id);
            //if (admissionFormViewModel == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(admissionFormViewModel);
            return View();
        }

        // POST: AdmissionForms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //AdmissionFormViewModel admissionFormViewModel = db.AdmissionFormViewModels.Find(id);
            // db.AdmissionFormViewModels.Remove(admissionFormViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public PartialViewResult ShowPartialView()
        {
            return PartialView("_CaptureImagePartialView");
        }

        public string savephoto()
        {
            string imageData = Request.Form["photo"];
            string path = null;
            if (imageData != "")
            {
                DateTime date = DateTime.UtcNow;
                path = "Photo " + date.ToString() + ".png";
                path = path.Replace("/", "-");
                path = path.Replace(":", "-");
                string Pic_Path = HttpContext.Server.MapPath("~/Content/Images/" + path);
                using (FileStream fs = new FileStream(Pic_Path, FileMode.Create))
                {
                    using (BinaryWriter bw = new BinaryWriter(fs))
                    {
                        byte[] data = Convert.FromBase64String(imageData);
                        bw.Write(data);
                        bw.Close();
                    }
                }

            }
            return "../Content/Images/" + path;
        }

        public JsonResult searchStudent(string name,int batchId)
        {
            int _centerid = CenterID();
            string json= JsonConvert.SerializeObject(db.StudentDetails.Where(x=>(x.CenterName.CenterId==_centerid && (x.Name.Contains(name) || x.Reg_No.ToString().Contains(name) || x.Contact_No.Contains(name) || x.Date_Of_Joining.ToString().Contains(name)))).ToList());
            return Json(json,JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

NICTERP/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NICTERP.Models;
using NICTERP.Models.View_Models;
using NICTERP.Models.NICT;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using System.Text;
namespace NICTERP.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private NICTDbContext db = new NICTDbContext();
        // GET: Dashboard
        protected int CenterID()
        {
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            return currentUser.CenterID;
        }
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult IncompleteForms()
        {
            int _centerid = CenterID();
            List<StudentDetail> students = db.StudentDetails.Where(x => x.AdmissionForm.Form_Complete == false && x.CenterName.CenterId == _centerid).OrderByDescending(y => y.AdmissionForm.Dated).Take(5).ToList();
            ViewBag.Count = db.StudentDetails.Where(x => x.AdmissionForm.Form_Complete == false && x.CenterName.CenterId == _centerid).Count();
            return PartialView("IncompleteForms", students);
        }

        public PartialViewResult PendingBalances()
        {
            int _centerid = CenterID();
            var a = from p in db.Installments
                    where p.AdmissionForm.Center.CenterId == _centerid
                    group p.Balance_Due by p.Form_No;
            int count = 0;
            foreach (var b in a)
            {
                long length = b.Count();
                var c = b.ToArray();
                if (c[length - 1] != 0)
                    count++;
            }
            @ViewBag.Count = count;
            List<long> formNos = db.AdmisionForms.Where(w => w.Center.CenterId == _centerid).OrderByDescending(o => o.Dated).Take(5).Select(x => x.Form_No).ToList();
            List<PendingBalances> pendingBalances = new List<PendingBalances>();
            foreach (long formno in formNos)
            {
                PendingBalances pendingBalance = new PendingBalances();
                pendingBalance.Installment = db.Installments.Where(w => w.Form_No == formno && w.AdmissionForm.Center.CenterId == _centerid).OrderByDescending(x => x.Datetime).First();
                pendingBalance.StudentDetail = db.StudentDetails.Where(w => w.Form_No == formno && w.CenterName.CenterId == _centerid).FirstOrDefault();
                pendingBalances.Add(pendingBalance);
            }
            return PartialView(pendingBalances);
        }

        public ActionResult TabIncompleteForms()
        {
            int _centerid = CenterID();
            List<StudentDetail> students = db.StudentDetails.Where(x => x.AdmissionForm.Form_Complete == false && x.CenterName.CenterId == _centerid).OrderByDescending(y => y.AdmissionForm.Dated).Take(5).ToList();
            string json = JsonConvert.SerializeObject(students);
            var sb = new StringBuilder();
            sb.AppendFormat("retry: 300000\n\ndata: {0}\n\n", json);
            return Content(sb.ToString(), "text/event-stream");
        }

        public ActionResult TabPendingBalances()
        {
            int _centerId = CenterID();
            List<long> formNos = db.AdmisionForms.Where(w => w.Center.CenterId == _centerId && w.Form_Complete==false).OrderByDescending(o => o.Dated).Select(x => x.Form_No).ToList();
            List<PendingBalances> _pendingBalances = new List<PendingBalances>();
            foreach (long formno in formNos)
            {
                PendingBalances pendingBalance = new PendingBalances();
                pendingBalance.Installment = db.Installments.Where(w => w.Form_No == formno && w.AdmissionForm.Center.CenterId == _centerId).OrderByDescending(x => x.Datetime).First();
                pendingBalance.StudentDetail = db.StudentDetails.Where(w => w.Form_No == formno && w.CenterName.CenterId == _centerId).FirstOrDefault();
                if (pendingBalance.Installment.Balance_Due != 0)
                    _pendingBalances.Add(pendingBalance);
            }
            string json = JsonConvert.SerializeObject(_pendingBalances);
            var sb = new StringBuilder();
            sb.AppendFormat("retry: 300000\n\ndata: {0}\n\n", json);
            return Content(sb.ToString(), "text/event-stream");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NICTERP/Controllers/RoleController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using NICTERP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NICTERP.Controllers
{
    [Authorize(Roles="Admin")]
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }



        /// <summary>
        /// Get All Roles
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        /// <summary>
        /// Create  a New role
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        /// <summary>
        /// Create a New Role
        /// </summary>
        /// <param name="Role"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
     
 
    }
}

NICTERP/Views/Shared/_AddInstallmentPartialView.cshtml
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
@model NICTERP.Models.NICT.Installment
@{long fn = ViewBag.FormNo;}
@using (Ajax.BeginForm(new AjaxOptions()
{
    Url = "/Installments/Create/" + fn,
    InsertionMode = InsertionMode.Replace,
    OnSuccess = "success",
    OnFailure = "failure"
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Form_No, htmlAttributes: new { @Value = fn })
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <table class="table">
            <tr>
                <th>Amount</th>
                <th>Datetime</th>
                <th>&nbsp;</th>
            </tr>
            <tr>
                <td>
                    @Html.EditorFor(model => model.Amount_Paid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Amount_Paid, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.EditorFor(model => model.Datetime, new { htmlAttributes = new { @class = "form-control datepicker", @Value = @DateTime.Now.ToLongDateString() } })
                    @Html.ValidationMessageFor(model => model.Datetime, "", new { @class = "text-danger" })
                </td>
                <td>
                    <input type="submit" value="Add" class="btn btn-primary" />
                </td>
            </tr>
        </table>
        <div class="form-group col-xs-6" style="padding:0;margin:0">
            <div class="col-md-10">


            </div>
        </div>

        <div class="form-group col-xs-6" style="padding:0;margin:0">

            <div class="col-md-10">


            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datetime")
}
<script src="~/Scripts/bootstrap-datepicker.min.js"></script>
<script>
    $('.datepicker').datepicker({
    });
</script>

NICTERP/Views/Shared/_CaptureImagePartialView.cshtml
<div class="container">

    <script>
        var canvas, context, video, videoObj, test;

        $(function () {
            canvas = document.getElementById("canvas");
            context = canvas.getContext("2d");
            video = document.getElementById("video");

            // different browsers provide getUserMedia() in differnt ways, so we need to consolidate
            navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

            if (navigator.getUserMedia) {
                navigator.getUserMedia(
                   { video: true }, // which media
                   function (stream) {   // success function
                       video.src = window.URL.createObjectURL(stream);
                       video.onloadedmetadata = function (e) {
                           video.play();
                           test = stream;
                       };
                   },
                   function (err) {  // error function
                       console.log("The following error occured: " + err.name);
                   }
              );
            }
            else {
                console.log("getUserMedia not supported");
            }
        });

        function takePhoto() {
            context.drawImage(video, 0, 0, 400, 300);
        }

        function savePhoto() {
            var data = canvas.toDataURL();
            data = data.replace(/^data:image\/(png|jpg);base64,/, "");
            var title = $("#title").val();

            $.ajax({
                type: "POST",
                url: "savephoto",
                data: {
                    photo: data,
                    title: title
                }
            }).done(function (o) {
                debugger;
                if (o != null || o != "") {
                    $(".img-thumbnail").attr("src", o);
                    $("#imgUrl").val(o);
                    $(".img-thumbnail").load();
                    $('.modal').modal('hide');
                    test.stop();
                    var successMsg = '<div class="alert alert-success fade in"> <a href="#" class="close" data-dismiss="alert">&times;</a>' +
    '<strong>Success!</strong> Your message has been sent successfully. &nbsp;</div>';
                    $("#noti").html(successMsg);
                }
                else {
                    var errorMsg = '<div class="alert alert-warning alert-dismissible" role="alert">' +
'<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>' +
'<strong>Oops!</strong> Error Saving Pic. &nbsp;</div>'
                    $("#noti").html(errorMsg);
                }
            });


        }
    </script>
    <video id="video" width="400" height="300" autoplay></video>
    <span id="snap" onclick="takePhoto()" class="btn btn-default">Snap</span>
    <canvas id="canvas" width="400" height="300"></canvas>




</div>

NICTERP/Views/Shared/_InstallmentsPartialView.cshtml
@model IEnumerable<NICTERP.Models.NICT.Installment>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Amount_Paid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance_Due)
        </th>
        <th>
            Dated
        </th>
        @*<th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr id="@item.Id" class="text-left">
        <td>
            @Html.DisplayFor(modelItem => item.Amount_Paid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Balance_Due)
        </td>
        <td>
            @item.Datetime.Date.AddHours(5).AddMinutes(30).ToLongDateString()
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>*@
    </tr>
}

</table>

NICTERP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("NICT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <a href="/Dashboard">
                    <img src="~/Content/Images/Logo.jpg" style="width:115px"/>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Dashboard")</li>
                    <li>@Html.ActionLink("Admission Form", "Create", "AdmissionForms")</li>
                    <li>@Html.ActionLink("Batch", "Index", "Batch")</li>
                    <li>@Html.ActionLink("Roles", "Index", "Role")</li>
                    <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - NICT SRM</p>
            <p style="text-align:right">Designed & Developed by <b>Gonick Nalwa</b></p>
        </footer>
    </div>

  

</body>
</html>